/**
 * preset-likes.js — curtidas iniciais a partir da playlist "Beno disco".
 * Na primeira abertura, o app marca como ❤️ as faixas abaixo que existirem
 * no acervo (uma vez só, por aparelho). Depois você pode descurtir à vontade.
 * Formato: [artista, título]
 */
window.PRESET_LIKES = [
  ["Gino Soccio", "Try It Out"],
  ["Gino Soccio", "It's Alright"],
  ["Gino Soccio", "I Wanna Take You There (Now)"],
  ["Gino Soccio", "You Move Me"],
  ['Jimmy "Bo" Horne', "Is It In"],
  ["Fantasy", "You're Too Late"],
  ["People's Choice", "Do It Any Way You Wanna"],
  ["War", "You Got the Power"],
  ["Firefly", "Love Is Gonna Be on Your Side"],
  ["Voyage", "I Love You Dancer"],
  ["B.T. Express", "Does It Feel Good"],
  ["Suzy Q", "Get On Up and Do It Again"],
  ["Unlimited Touch", "I Hear Music in the Streets"],
  ["Unlimited Touch", "Happy Ever After"],
  ["Unlimited Touch", "Searching to Find the One"],
  ["The Strikers", "Inch by Inch"],
  ["The Strikers", "Body Music"],
  ["Sharon Redd", "Can You Handle It"],
  ["Geraldine Hunt", "Can't Fake the Feeling"],
  ["Instant Funk", "Everybody"],
  ["Gayle Adams", "Love Fever"],
  ["Gayle Adams", "Let's Go All the Way"],
  ["Gayle Adams", "I Loved Every Minute of It"],
  ["Bobby Thurston", "Check Out the Groove"],
  ["Stargard", "Wear It Out"],
  ["Narada Michael Walden", "Tonight I'm Alright"],
  ["Midnight Magic", "Beam Me Up"],
  ["Goldie Alexander", "Show You My Love"],
  ["Gwen Guthrie", "It Should Have Been You"],
  ["Imagination", "Burnin' Up"],
  ["Empress", "Dyin' to Be Dancin'"],
  ["Carrie Lucas", "Dance with You"],
  ["Raw Silk", "Just in Time"],
  ["Raw Silk", "Do It to the Music"],
  ["Gwen McCrae", "Doin' It"],
  ["Roy B", "If You Want Me"],
  ["Mtume", "So You Wanna Be a Star"],
  ["High Fashion", "Feelin' Lucky Lately"],
  ["Loose Joints", "Is It All Over My Face"],
  ["The B.B. & Q. Band", "Imagination"],
  ["Chic", "Chic Cheer"],
  ["Musique", "Keep On Jumpin'"],
  ["The Salsoul Orchestra", "Runaway"],
];
